---
new_page_extension: md
auto_deploy: false
admin_path: superadmin
webhook_url: 
sections:
- type: directory
  path: contentdir
  label: "\U0001F3E0 Home"
  create: all
  match: "**/*"
- type: heading
  label: Open Menu
- type: document
  path: blog
  label: "\U0001F680 Blog"
  read_only: true
- type: document
  path: doc
  label: "\U0001F4BB Doc"
- type: document
  path: developer
  label: "\U0001F468\U0001F3FB‍\U0001F680 Developer"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
