---
new_page_extension: md
auto_deploy: false
admin_path: superadmin
webhook_url: 
sections:
- type: heading
  label: Open Menu
- type: directory
  path: contentdir
  label: "\U0001F3E0 Home"
  create: all
  match: cuteblog/src/pages/posts
  templates:
  - other-contents
  - posts
  - blog-posts
- type: directory
  path: docsdev
  label: "\U0001F4BB Doc"
  create: all
  match: cuteblog/src/pages/posts
  templates:
  - blog-posts
  - posts
  - other-contents
- type: directory
  path: blogpost
  label: "\U0001F680 Blog"
  create: all
  match: cuteblog/src/pages/posts
  templates:
  - blog-posts
  - other-contents
  - posts
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/path/to/media"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
